### ISSUE TITLE
Makie support?

### ISSUE THREAD

**Issue by jw3126** [JuliaGeo/GeoInterface.jl#70]
There is GeoInterfaceRecipes which gives Plots.jl support for anything that implements GeoInterface.
Is there something similar for Makie support?
I did not find anything and put together a small [package](https://github.com/jw3126/GeoInterfaceMakie.jl) myself. 
Just want to double check I am not reinventing wheels here before registering that package.

**Comment by visr** [comment]
That's interesting, thanks for sharing. Are you aware of [GeoMakie](https://github.com/MakieOrg/GeoMakie.jl)? Makie itself uses [GeometryBasics](https://github.com/JuliaGeometry/GeometryBasics.jl/) geometry types, and since GeometryBasics implements the GeoInterface as well, this should allow GeoMakie to accept other geometry types as well.

**Comment by jw3126** [comment]
What I am interested in doing is plotting LibGEOS stuff with Makie. I looked briefly at GeoMakie before it looks like a powerful package. However my impression was that it is geared towards plotting geographical data and does not really help with plotting say a LibGEOS.Polygon?

**Comment by rafaqz** [comment]
That's great. This actually came up with @SimonDanisch the other day.

If you give me a few days I can go over the code if that would help.

And do you want to put it in JuliaGeo?

**Comment by jw3126** [comment]
> If you give me a few days I can go over the code if that would help.

Awesome @rafaqz I would appreciate that.

> And do you want to put it in JuliaGeo?

Sure! Do you think it makes sense to put it here in the repo as a subpackage analogous to GeoInterfaceRecipes?

**Comment by rafaqz** [comment]
Yeah it can go in here as well, that's even simpler.

**Comment by visr** [comment]
> my impression was that it is geared towards plotting geographical data and does not really help with plotting say a LibGEOS.Polygon

I'd think the latter would also be a usecase for GeoMakie, although most examples are world maps. If you prefer to have a separate GeoInterfaceMakie that does not deal with projections and such, we could make GeoMakie depend on GeoInterfaceMakie. Only reason I'm slightly hesistant is that I don't see much advantage in splitting the packages other than avoiding perhaps a PROJ dependency.

**Comment by rafaqz** [comment]
I guess we need to think about what default plots should be.

I feel that simple 2d plots without projections to be the default? and just using `plot(geom)` rather than defining a `GeoAxis` manually?

For `plot(geom)` to work on package types, packages will need depend on a generic GeoInterface plotting package like what @jw3126 has written. That could be build into GeoMakie.jl but it has a _lot_ of dependencies: https://github.com/MakieOrg/GeoMakie.jl/blob/master/Project.toml

So maybe GeoMakie.jl building off GeoInterfaceMakie.jl would be best?

@jw3126 the code looks good, a small change could be in `points` - iterating over the `getgeom(obj)` and calling `convert` on the points rather than calling `coordinates(obj)`. It should halve the allocations as `getgeom` returns an iterator.

If @visr is happy to include this here you could make a PR as a subpackage?

**Comment by visr** [comment]
No objections from me, just making sure there is a clear scope/story for GeoInterfaceMakie and GeoMakie. It sounds like there is one :)

**Comment by asinghvi17** [comment]
Just saw this issue - definitely agree.  GeoMakie was always more oriented towards supporting projections, so GeoInterfaceMakie taking care of conversions works splendidly!
