### ISSUE TITLE
Allow plotting Vectors of geometries with GeoInterfaceMakie.jl

### ISSUE THREAD

**Issue by rafaqz** [JuliaGeo/GeoInterface.jl#79]
Makie lets you do this with GeometryBasics.jl types, so probably should for all GeoInterface.jl types.

**Comment by asinghvi17** [comment]
The only real work needed here is what happens if you have a vector which contains both Polygon and MultiPolygon. 
 Currently, `GI.convert.(GB, geoms)` results in a `Vector{Any}`, which is not really plottable.  Should we change the type of the array in GeoInterfaceMakie if the only unique types are a trait and its multi version?

Similarly, trying to plot `Union{GB.Polygon, GB.MultiPolygon[some_gb_poly, GB.MultiPolygon([some_gb_poly])]` fails.  What I do for now is force everything to MultiPolygon, but it's not really a great solution.

**Comment by rafaqz** [comment]
Yeah, that is a problem. We clearly can't dispatch in `Any`.

I guess using just `FeatureCollection` wrappers for everything is a solution? And making recipes for those?

See my wrapper types PR here.

**Comment by asinghvi17** [comment]
Hmm, that does look interesting.  A couple of thoughts come to mind:

What do we do if someone passes a feature collection with a bunch of polys and a couple of points, or lines, or meshes to e.g. `poly`?  Should we directly error out?

It would be nice to allow `poly(fc::FeatureCollection; color = :column_of_fc)`, but it seems infeasible with how Makie is structured.  Perhaps we could create a mechanism to add hooks to the standard `color_and_colormap!` function which gets the colorrange etc, which could detect whether the input is a FeatureCollection and if so what to do about it.  Or, we could hook in by just defining `plot!(poly::Poly{<: Tuple{<: FeatureCollection}}})`, which actually doesn't sound so bad now that I think about it.

**Comment by rafaqz** [comment]
Yeah, there will be some work to get it to do smart things like different shapes and colours per object.

But one we have dispatched on the FeatureCollection we can do that however we like. But maybe using glue packages and a Makie.jl dep will be needed.

**Comment by visr** [comment]
@rafaqz Should this be closed now that #108 is merged? Perhaps good to make a GeoInterfaceMakie tag as well?
